const notificacoes = () => ([
  {
    id: 1,
    title: 'Leito 204B',
    description: 'Paciente teve alta. Leito precisa de limpeza terminal.',
    status: 'limpeza',
    priority: 'alta',
    patientName: 'Carlos Almeida',
    responsible: 'Equipe de Limpeza',
    isCompleted: false,
  },
  {
    id: 2,
    title: 'Quarto 302',
    description: 'Ar-condicionado com vazamento de água.',
    status: 'manutencao',
    priority: 'media',
    patientName: 'Fernanda Ribeiro',
    responsible: 'Manutenção Predial',
    isCompleted: false,
  },
  {
    id: 3,
    title: 'Sala Procedimentos 2',
    description: 'Desinfecção necessária após procedimento infectante.',
    status: 'limpeza',
    priority: 'alta',
    patientName: '',
    responsible: 'Equipe de Limpeza',
    isCompleted: true,
  },
  {
    id: 4,
    title: 'Corredor Ala 1B',
    description: 'Reposição de 3 lâmpadas queimadas.',
    status: 'manutencao',
    priority: 'baixa',
    patientName: '',
    responsible: 'Manutenção Elétrica',
    isCompleted: false,
  },
  {
    id: 5,
    title: 'Leito 105A',
    description: 'Leito limpo e pronto para uso.',
    status: 'limpeza',
    priority: 'baixa',
    patientName: '',
    responsible: 'Equipe de Limpeza',
    isCompleted: true,
  },
  {
    id: 6,
    title: 'Quarto 401',
    description: 'Equipamento de oxigênio fazendo ruído anormal.',
    status: 'manutencao',
    priority: 'alta',
    patientName: 'João da Silva',
    responsible: 'Manutenção Técnica',
    isCompleted: false,
  },
  {
    id: 7,
    title: 'Leito 207C',
    description: 'Paciente solicitou troca de lençóis.',
    status: 'limpeza',
    priority: 'media',
    patientName: 'Luciana Costa',
    responsible: 'Equipe de Limpeza',
    isCompleted: true,
  },
  {
    id: 8,
    title: 'Enfermaria 3',
    description: 'Pia entupida sem vazão.',
    status: 'manutencao',
    priority: 'media',
    patientName: '',
    responsible: 'Manutenção Hidráulica',
    isCompleted: false,
  },
  {
    id: 9,
    title: 'Centro Cirúrgico',
    description: 'Recolher lixo contaminado pós-cirurgia.',
    status: 'limpeza',
    priority: 'alta',
    patientName: '',
    responsible: 'Higienização Técnica',
    isCompleted: false,
  },
  {
    id: 10,
    title: 'Elevador Pediatria',
    description: 'Elevador travou momentaneamente no 2º andar.',
    status: 'manutencao',
    priority: 'media',
    patientName: '',
    responsible: 'Manutenção Predial',
    isCompleted: false,
  },
]);

export default notificacoes;

